# Generated by Django 6.0.1 on 2026-02-07 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_ledgerentry'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ledgerentry',
            options={'verbose_name': 'Ledger Entry', 'verbose_name_plural': 'Ledger Entries'},
        ),
        migrations.AddField(
            model_name='transaction',
            name='narration',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
